#!/usr/bin/env python
# ~*~ coding: utf-8 ~*~
#
from __future__ import absolute_import

from rest_framework_bulk.routes import BulkRouter

from .. import api

app_name = '{app_name}s'

router = BulkRouter()
router.register(r'{app_name}s', api.{app_name_first_uppercase}ViewSet, '{app_name}')

urlpatterns = [

]

urlpatterns += router.urls
