# Generated by Django 2.1.7 on 2019-09-02 06:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
                ('principal', models.CharField(max_length=128, verbose_name='Principal')),
                ('principal_duty', models.CharField(max_length=128, verbose_name='Principal duty')),
                ('principal_ecard', models.CharField(max_length=128, unique=True, verbose_name='Principal ecard')),
                ('principal_email', models.EmailField(max_length=128, unique=True, verbose_name='Principal Email')),
                ('principal_phone', models.CharField(max_length=20, verbose_name='Principal phone')),
                ('coordinator', models.CharField(max_length=128, verbose_name='Coordinator')),
                ('coordinator_duty', models.CharField(max_length=128, verbose_name='Coordinator duty')),
                ('coordinator_ecard', models.CharField(max_length=128, unique=True, verbose_name='Coordinator ecard')),
                ('coordinator_email', models.EmailField(max_length=128, unique=True, verbose_name='Coordinator Email')),
                ('coordinator_phone', models.CharField(max_length=20, verbose_name='Coordinator phone')),
                ('coordinator_qq', models.CharField(max_length=128, verbose_name='Coordinator qq')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
            ],
            options={
                'verbose_name': 'Department',
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
                ('homepage_url', models.URLField(max_length=128, unique=True, verbose_name='Homepage URL')),
                ('admin_url', models.URLField(blank=True, max_length=256, null=True, verbose_name='Admin URL')),
                ('admin_staff', models.CharField(max_length=128, verbose_name='Admin staff')),
                ('admin_staff_phone', models.CharField(max_length=20, verbose_name='Admin staff phone')),
                ('department', models.CharField(max_length=128, verbose_name='Department')),
                ('created_by', models.CharField(blank=True, max_length=30, null=True, verbose_name='Created by')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
            ],
            options={
                'verbose_name': 'System',
            },
        ),
    ]
