# Generated by Django 2.1.7 on 2019-09-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='coordinator_qq',
            field=models.CharField(max_length=128, verbose_name='Coordinator QQ'),
        ),
    ]
