# Generated by Django 2.1.7 on 2019-09-17 02:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0003_auto_20190907_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainName',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Name')),
                ('ip', models.CharField(blank=True, max_length=128, null=True, verbose_name='Ip')),
                ('type', models.CharField(blank=True, max_length=128, null=True, verbose_name='Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('comment', models.CharField(blank=True, max_length=128, null=True, verbose_name='Comment')),
                ('created_by', models.CharField(blank=True, max_length=30, null=True, verbose_name='Created by')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
            ],
            options={
                'verbose_name': 'DomainName',
            },
        ),
    ]
