# Generated by Django 2.1.7 on 2019-09-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0004_domainname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domainname',
            options={'verbose_name': 'Domain name'},
        ),
        migrations.AlterField(
            model_name='domainname',
            name='ip',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='domainname',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Domain name'),
        ),
        migrations.AlterField(
            model_name='domainname',
            name='type',
            field=models.CharField(choices=[('A', 'normal ex: zb IN A 202.195.160.31'), ('asp2', '78_ASP server'), ('wwwsub', 'PHP server'), ('rproxy', 'Reverse proxy'), ('httpsvr', 'httpsvr'), ('asp3', '73_ASP server'), ('wzq', 'WZQ server'), ('a10jiaoyuwang', 'A10 jiaoyuwang proxy'), ('a10xiaonei', 'A10 jiaoyuwang proxy')], default='A', max_length=128, verbose_name='Type'),
        ),
    ]
